version: '3'

services:
  eth-node:
    tty: true
    build: .
    container_name: test
    hostname: test
    ports:
      - 8545:8545
      - 3000:3000
    volumes:
      - /home/titan/Titan/github/blockchain/eth-poc/newNode/volumes:/volumes